language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make test

after_sukcess:
  - make docker_build
  - make docker_push
  - make test_xunit

deploy:
  provider: heroku
  app: gentle-atoll-88129
  api_key: ${HEROKU_API_KEY}
