language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make lint
  - make test_xunit

after_sukcess:
  - make docker_build
  - make docker_push


deploy:
  provider: heroku
  app: gentle-atoll-88129
  api_key: ${HEROKU_API_KEY}
